using FinanceAPI.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace FinanceAPI.Infrastructure.Database;
public static class DatabaseSeed
{
    public static void Seed(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>().HasData(
            new Department { Id = 1, Name = "Office of the Minister", Status = "I" },
            new Department { Id = 2, Name = "Office of Secretary of State ", Status = "I" },
            new Department { Id = 3, Name = "Accounts", Status = "I" },
            new Department { Id = 4, Name = "Asset Management Unit", Status = "I" },
            new Department { Id = 5, Name = "Debt Management Unit", Status = "I" },
            new Department { Id = 6, Name = "Procurement Oversight Unity (POU)", Status = "I" },
            new Department { Id = 7, Name = "Macro-Economic Forecasting Analyst Branch (MFAB)", Status = "I" },
            new Department { Id = 8, Name = "Human Resources", Status = "I" },
            new Department { Id = 9, Name = "Administration", Status = "I" },
            new Department { Id = 10, Name = "System Support", Status = "I" },
            new Department { Id = 11, Name = "Financial Planning and Control", Status = "I" },
            new Department { Id = 12, Name = "Public Investment Management", Status = "I" },
            new Department { Id = 13, Name = "Public Budget Management", Status = "I" },
            new Department { Id = 14, Name = "Public Accounts Management", Status = "I" },
            new Department { Id = 15, Name = "Treasury", Status = "I" },
            new Department { Id = 16, Name = "Tax & Sectorial Policy", Status = "I" },
            new Department { Id = 17, Name = "Financial Services Development", Status = "I" },
            new Department { Id = 18, Name = "Internal Audit", Status = "I" },
            new Department { Id = 19, Name = "Trade", Status = "I" },
            new Department { Id = 20, Name = "National Planning", Status = "I" }
        );

        modelBuilder.Entity<PostTitle>().HasData(
            new PostTitle { Id = 1, Name = "Accountant", Status = "I" },
            new PostTitle { Id = 2, Name = "Accountant General", Status = "I" },
            new PostTitle { Id = 3, Name = "Accounts Administrator", Status = "I" },
            new PostTitle { Id = 4, Name = "Accounts Technician", Status = "I" },
            new PostTitle { Id = 5, Name = "Administrative Offcier", Status = "I" },
            new PostTitle { Id = 6, Name = "Adviser, Technical", Status = "I" },
            new PostTitle { Id = 7, Name = "Asset Management Controller", Status = "I" },
            new PostTitle { Id = 8, Name = "Asset Management Officer", Status = "I" },
            new PostTitle { Id = 9, Name = "Assistant Accountant", Status = "I" },
            new PostTitle { Id = 10, Name = "Assistant Accounts Administrator", Status = "I" },
            new PostTitle { Id = 11, Name = "Assistant Administrative Officer", Status = "I" },
            new PostTitle { Id = 12, Name = "Assistant Asset Management Officer", Status = "I" },
            new PostTitle { Id = 13, Name = "Assistant Data Processing", Status = "I" },
            new PostTitle { Id = 14, Name = "Assistant Finance Analyst", Status = "I" },
            new PostTitle { Id = 15, Name = "Assistant Finance Officer", Status = "I" },
            new PostTitle { Id = 16, Name = "Assistant Internal Auditor", Status = "I" },
            new PostTitle { Id = 17, Name = "Assistant Procurement Analyst", Status = "I" },
            new PostTitle { Id = 18, Name = "Assistant Procurement Inspector", Status = "I" },
            new PostTitle { Id = 19, Name = "Assistant Systems Support Officer", Status = "I" },
            new PostTitle { Id = 20, Name = "Assistant Treasury Accountant - Payroll", Status = "I" },
            new PostTitle { Id = 21, Name = "Bursar", Status = "I" },
            new PostTitle { Id = 22, Name = "Chairman", Status = "I" },
            new PostTitle { Id = 23, Name = "Chief Accountant (Treasury)", Status = "I" },
            new PostTitle { Id = 24, Name = "Chief Executive Officer", Status = "I" },
            new PostTitle { Id = 25, Name = "Chief Internal Auditor", Status = "I" },
            new PostTitle { Id = 26, Name = "Comptroller General", Status = "I" },
            new PostTitle { Id = 27, Name = "Contract Manager", Status = "I" },
            new PostTitle { Id = 28, Name = "Customer Service Assistant", Status = "I" },
            new PostTitle { Id = 29, Name = "Debt Analyst", Status = "I" },
            new PostTitle { Id = 30, Name = "Deputy Chief Internal Auditior", Status = "I" },
            new PostTitle { Id = 31, Name = "Director", Status = "I" },
            new PostTitle { Id = 32, Name = "Director Asset Management", Status = "I" },
            new PostTitle { Id = 33, Name = "Director General", Status = "I" },
            new PostTitle { Id = 34, Name = "Director General HRM", Status = "I" },
            new PostTitle { Id = 35, Name = "Director General MFAB", Status = "I" },
            new PostTitle { Id = 36, Name = "Director Oversight Procurement Unit", Status = "I" },
            new PostTitle { Id = 37, Name = "Director, Administration", Status = "I" },
            new PostTitle { Id = 38, Name = "Driver", Status = "I" },
            new PostTitle { Id = 39, Name = "Driver, Senior", Status = "I" },
            new PostTitle { Id = 40, Name = "Driver/ Messenger", Status = "I" },
            new PostTitle { Id = 41, Name = "Economist", Status = "I" },
            new PostTitle { Id = 42, Name = "Executive Director", Status = "I" },
            new PostTitle { Id = 43, Name = "Facilities Technician", Status = "I" },
            new PostTitle { Id = 44, Name = "Finance Analyst", Status = "I" },
            new PostTitle { Id = 45, Name = "Financial Analyst", Status = "I" },
            new PostTitle { Id = 46, Name = "Financial Controller", Status = "I" },
            new PostTitle { Id = 47, Name = "Housekeeper", Status = "I" },
            new PostTitle { Id = 48, Name = "HR & Budget Management Officer", Status = "I" },
            new PostTitle { Id = 49, Name = "Information and Communication Officer", Status = "I" },
            new PostTitle { Id = 50, Name = "Internal Audit Technician", Status = "I" },
            new PostTitle { Id = 51, Name = "Internal Auditor", Status = "I" },
            new PostTitle { Id = 52, Name = "Office Assistant", Status = "I" },
            new PostTitle { Id = 53, Name = "Personal Assistant", Status = "I" },
            new PostTitle { Id = 54, Name = "Policy Analyst", Status = "I" },
            new PostTitle { Id = 55, Name = "Postal Regulator", Status = "I" },
            new PostTitle { Id = 56, Name = "Principal Debt Analyst", Status = "I" },
            new PostTitle { Id = 57, Name = "Principal Economist", Status = "I" },
            new PostTitle { Id = 58, Name = "Principal Finance Analyst", Status = "I" },
            new PostTitle { Id = 59, Name = "Principal Internal Auditor", Status = "I" },
            new PostTitle { Id = 60, Name = "Principal Procurement Analyst", Status = "I" },
            new PostTitle { Id = 61, Name = "Principal Project Accountant", Status = "I" },
            new PostTitle { Id = 62, Name = "Principal Secretary", Status = "I" },
            new PostTitle { Id = 63, Name = "Principal Secretary, Finance", Status = "I" },
            new PostTitle { Id = 64, Name = "Principal Trade Officer", Status = "I" },
            new PostTitle { Id = 65, Name = "Private Secretary", Status = "I" },
            new PostTitle { Id = 66, Name = "Private Secretary, Senior", Status = "I" },
            new PostTitle { Id = 67, Name = "Procurement Analyst", Status = "I" },
            new PostTitle { Id = 68, Name = "Procurement Inspector", Status = "I" },
            new PostTitle { Id = 69, Name = "Procurement Officer", Status = "I" },
            new PostTitle { Id = 70, Name = "Records Assistant", Status = "I" },
            new PostTitle { Id = 71, Name = "Secretary of State", Status = "I" },
            new PostTitle { Id = 72, Name = "Senior Accountant", Status = "I" },
            new PostTitle { Id = 73, Name = "Senior Accounts Administrator", Status = "I" },
            new PostTitle { Id = 74, Name = "Senior Accounts Assistant", Status = "I" },
            new PostTitle { Id = 75, Name = "Senior Administrator Officer", Status = "I" },
            new PostTitle { Id = 76, Name = "Senior Analyst Programmer", Status = "I" },
            new PostTitle { Id = 77, Name = "Senior Asset Management Officer", Status = "I" },
            new PostTitle { Id = 78, Name = "Senior Debt Analyst", Status = "I" },
            new PostTitle { Id = 79, Name = "Senior Economist", Status = "I" },
            new PostTitle { Id = 80, Name = "Senior Finance Analyst", Status = "I" },
            new PostTitle { Id = 81, Name = "Senior Internal Auditor", Status = "I" },
            new PostTitle { Id = 82, Name = "Senior Investigation Officer", Status = "I" },
            new PostTitle { Id = 83, Name = "Senior Office Assistant", Status = "I" },
            new PostTitle { Id = 84, Name = "Senior Office Officer", Status = "I" },
            new PostTitle { Id = 85, Name = "Senior Policy Analyst", Status = "I" },
            new PostTitle { Id = 86, Name = "Senior Processing Officer", Status = "I" },
            new PostTitle { Id = 87, Name = "Senior Procurement Analyst", Status = "I" },
            new PostTitle { Id = 88, Name = "Senior Procurement Officer", Status = "I" },
            new PostTitle { Id = 89, Name = "Senior Project Accountant", Status = "I" },
            new PostTitle { Id = 90, Name = "Senior Project Officer", Status = "I" },
            new PostTitle { Id = 91, Name = "Senior Quantity Surveyor", Status = "I" },
            new PostTitle { Id = 92, Name = "Senior Trade Officer", Status = "I" },
            new PostTitle { Id = 93, Name = "Senior Trades Officer", Status = "I" },
            new PostTitle { Id = 94, Name = "Store Officer", Status = "I" },
            new PostTitle { Id = 95, Name = "Systems Support Manager", Status = "I" },
            new PostTitle { Id = 96, Name = "Systems Support Officer", Status = "I" },
            new PostTitle { Id = 97, Name = "Telephone Operator", Status = "I" },
            new PostTitle { Id = 98, Name = "Trades Officer", Status = "I" },
            new PostTitle { Id = 99, Name = "Transport Officer", Status = "I" }
        );
    }
}
