// <auto-generated />
using System;
using FinanceAPI.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250318103451_Added_Users_Table")]
    partial class Added_Users_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceAPI.Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Office of the Minister",
                            Status = "I"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office of Secretary of State ",
                            Status = "I"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accounts",
                            Status = "I"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Asset Management Unit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Debt Management Unit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Procurement Oversight Unity (POU)",
                            Status = "I"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Macro-Economic Forecasting Analyst Branch (MFAB)",
                            Status = "I"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Human Resources",
                            Status = "I"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Administration",
                            Status = "I"
                        },
                        new
                        {
                            Id = 10,
                            Name = "System Support",
                            Status = "I"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Financial Planning and Control",
                            Status = "I"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Public Investment Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Public Budget Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Public Accounts Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Treasury",
                            Status = "I"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Tax & Sectorial Policy",
                            Status = "I"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Financial Services Development",
                            Status = "I"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Internal Audit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Trade",
                            Status = "I"
                        },
                        new
                        {
                            Id = 20,
                            Name = "National Planning",
                            Status = "I"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateJoined")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PostTitleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.PostTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accountant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accountant General",
                            Status = "I"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accounts Administrator",
                            Status = "I"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accounts Technician",
                            Status = "I"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Administrative Offcier",
                            Status = "I"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Adviser, Technical",
                            Status = "I"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Asset Management Controller",
                            Status = "I"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Asset Management Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Assistant Accountant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Assistant Accounts Administrator",
                            Status = "I"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Assistant Administrative Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Assistant Asset Management Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Assistant Data Processing",
                            Status = "I"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Assistant Finance Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Assistant Finance Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Assistant Internal Auditor",
                            Status = "I"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Assistant Procurement Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Assistant Procurement Inspector",
                            Status = "I"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Assistant Systems Support Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Assistant Treasury Accountant - Payroll",
                            Status = "I"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bursar",
                            Status = "I"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Chairman",
                            Status = "I"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Chief Accountant (Treasury)",
                            Status = "I"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Chief Executive Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Chief Internal Auditor",
                            Status = "I"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Comptroller General",
                            Status = "I"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Contract Manager",
                            Status = "I"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Customer Service Assistant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Debt Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Deputy Chief Internal Auditior",
                            Status = "I"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Director",
                            Status = "I"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Director Asset Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Director General",
                            Status = "I"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Director General HRM",
                            Status = "I"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Director General MFAB",
                            Status = "I"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Director Oversight Procurement Unit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Director, Administration",
                            Status = "I"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Driver",
                            Status = "I"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Driver, Senior",
                            Status = "I"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Driver/ Messenger",
                            Status = "I"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Economist",
                            Status = "I"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Executive Director",
                            Status = "I"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Facilities Technician",
                            Status = "I"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Finance Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Financial Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Financial Controller",
                            Status = "I"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Housekeeper",
                            Status = "I"
                        },
                        new
                        {
                            Id = 48,
                            Name = "HR & Budget Management Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Information and Communication Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Internal Audit Technician",
                            Status = "I"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Internal Auditor",
                            Status = "I"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Office Assistant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Personal Assistant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Policy Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Postal Regulator",
                            Status = "I"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Principal Debt Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Principal Finance Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Principal Internal Auditor",
                            Status = "I"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Principal Procurement Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Principal Project Accountant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Principal Secretary, Finance",
                            Status = "I"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Principal Trade Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Prinicipal Economist",
                            Status = "I"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Prinicipal Secreatary",
                            Status = "I"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Private Secretary",
                            Status = "I"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Private Secretary, Senior",
                            Status = "I"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Procurement Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Procurement Inspector",
                            Status = "I"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Procurement Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Records Assistant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Secretary of State",
                            Status = "I"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Senior Accountant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Senior Accounts Administrator",
                            Status = "I"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Senior Accounts Assistant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Senior Administrator Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Senior Analyst Programmer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Senior Asset Management Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Senior Debt Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Senior Economist",
                            Status = "I"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Senior Finance Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Senior Internal Auditor",
                            Status = "I"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Senior Investigation Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Senior Office Assistant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Senior Office Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Senior Policy Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Senior Processing Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Senior Procurement Analyst",
                            Status = "I"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Senior Procurement Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Senior Project Accountant",
                            Status = "I"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Senior Project Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Senior Quantity Surveyor",
                            Status = "I"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Senior Trade Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Senior Trades Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Store Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Systems Support Manager",
                            Status = "I"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Systems Support Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Telephone Operator",
                            Status = "I"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Trades Officer",
                            Status = "I"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Transport Officer",
                            Status = "I"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.Employee", b =>
                {
                    b.HasOne("FinanceAPI.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceAPI.Domain.Models.PostTitle", "PostTitle")
                        .WithMany()
                        .HasForeignKey("PostTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("PostTitle");
                });
#pragma warning restore 612, 618
        }
    }
}
