// <auto-generated />
using System;
using FinanceAPI.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250220051056_Populate_Seed_Reference_Values")]
    partial class Populate_Seed_Reference_Values
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceAPI.Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Office of the Minister",
                            Status = "I"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office of Secretary of State ",
                            Status = "I"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accounts",
                            Status = "I"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Asset Management Unit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Debt Management Unit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Procurement Oversight Unity (POU)",
                            Status = "I"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Macro-Economic Forecasting Analyst Branch (MFAB)",
                            Status = "I"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Human Resources",
                            Status = "I"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Administration",
                            Status = "I"
                        },
                        new
                        {
                            Id = 10,
                            Name = "System Support",
                            Status = "I"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Financial Planning and Control",
                            Status = "I"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Public Investment Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Public Budget Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Public Accounts Management",
                            Status = "I"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Treasury",
                            Status = "I"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Tax & Sectorial Policy",
                            Status = "I"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Financial Services Development",
                            Status = "I"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Internal Audit",
                            Status = "I"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Trade",
                            Status = "I"
                        },
                        new
                        {
                            Id = 20,
                            Name = "National Planning",
                            Status = "I"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateJoined")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PostTitleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.PostTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Secretary of State",
                            Status = "I"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Principal Secretary",
                            Status = "I"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chairman",
                            Status = "I"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Senior Analyst Programmer",
                            Status = "I"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Models.Employee", b =>
                {
                    b.HasOne("FinanceAPI.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceAPI.Domain.Models.PostTitle", "PostTitle")
                        .WithMany()
                        .HasForeignKey("PostTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("PostTitle");
                });
#pragma warning restore 612, 618
        }
    }
}
